### ISSUE TITLE
Contribute this to conda-forge?

### ISSUE THREAD

**Issue by jnothman** [stuarteberg/graph-tool-feedstock#1]
I think it would be useful to have this maintained on conda-forge. Do you intend to contribute this there?

**Comment by stuarteberg** [comment]
I did originally, but there are a few sticking points.  Here are the issues I can think of:

- `graph-tool` requires gcc-5 or greater.  At the time I wrote this recipe, conda-forge supported only gcc-4.  Nowadays, conda-forge supports gcc-7 via Anaconda-provided compiler packages, so it might be possible to get a build working if we make some changes to `conda-forge.yml`.  The resulting packages would go to an auxillary label on the conda-forge channel (`gcc7`).

- On a related point, this recipe currently sets `_GLIBCXX_USE_CXX11_ABI=0`, to remain compatible with libraries that were built with gcc-4.  Presumably, we should remove that, and just force people to obtain ALL of their C++ packages from `conda-forge/label/gcc7` if they want to use this package.  Alternatively, we could build two versions (one with each ABI), but I don't know if there's a precedence for that in conda-forge.

- The dependencies must also be built with the new ABI, and uploaded to the `gcc7` label.  For example, it looks like [`sparsehash` is good to go][sparsehash], but [`cgal` is not][cgal].  Presumably, [this PR][cgal-pr] needs to be debugged first.  Looks like `cairomm` is in a [similar situation][cairomm-pr], but I think those are the only remaining unported dependencies.

[sparsehash]: https://anaconda.org/conda-forge/sparsehash/files
[cgal]: https://anaconda.org/conda-forge/cgal/files
[cgal-pr]: https://github.com/conda-forge/cgal-feedstock/pull/41
[cairomm-pr]: https://github.com/conda-forge/cairomm-feedstock/pull/11

- This package takes hours to build.  conda-forge relies on free compute time from the CI services (Travis, Circle, Appveyor), and the build will time out before the package is complete.  In the past, the only workaround was to get a volunteer to build it locally and upload the packages manually.  (I did that for Qt-5.6 at one point.)  I don't know if there's a better solution nowadays, so we should ask some conda-forge experts.

- The recipe builds graph-tool 2.26, but we should upgrade to 2.27.

- Of course, we should un-pin `boost` so that we get the standard version that conda-forge uses these days.

Given the issues with `cgal` and `cairomm`, it probably doesn't make sense to rush forward with a new PR just yet.  We should revisit this question again once those are sorted out.  If you'd like to help prod this along, I guess those two PRs are the right place to start.

FWIW, the binaries for `graph-tool 2.26` that came from this recipe are available on the following channel.  (But please note the caveat above about the ABI, if that matters to you.)

https://anaconda.org/flyem-forge/graph-tool/files

**Comment by jnothman** [comment]
Yes, I've been very glad for your channel. Thank you!

Thanks for explaining why it's not going to easily work with conda-forge.

An update to 2.27 on flyem-forge would be welcome, but no hurry from me.

FWIW, in order to get graph-tool working I also needed gtk3 for which I
needed the pkgw/label/superseded channel.

So I use

conda install -c conda-forge -c flyem-forge -c pkgw/label/superseded
graph-tool pygobject cairo gtk3

**Comment by stuarteberg** [comment]
@jnothman -- Thanks to improvements in conda-forge's infrastructure and package support, all of the issues mentioned above have been resolved.  It is now possible to host a build of `graph-tool` on conda-forge.  In fact, I've created a [feedstock][1] and the first build was uploaded to the `conda-forge` channel today.

[1]: https://github.com/conda-forge/graph-tool-feedstock

**Note:** The `gtk+3` issue you mentioned above is still a problem, so plotting doesn't work out-of-the-box.
